/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef user_profile_CONSTANTS_H
#define user_profile_CONSTANTS_H

#include "user_profile_types.h"

namespace Task1 {

class user_profileConstants {
 public:
  user_profileConstants();

};

extern const user_profileConstants g_user_profile_constants;

} // namespace

#endif
